### ISSUE TITLE
excel file template

### ISSUE THREAD

**Issue by AmrELZeky** [debiprasad/certificate-generator#1]
I cant find any excel  file attached to the example , could you please attach excel file template for this example.
it should be in storage/app/devlympics_2016.xlsx

**Comment by debiprasad** [comment]
It's a simple spreadsheet having 3 sheets. The first sheet has one column with the emails of participants who had completed the competition. The second sheet has one column with the emails of all participants. The third sheet is a map between the name of the participants and their email IDs. It has two columns. The first column has all email IDs and the second column has names of the participants. There are no headers in any of the columns in all three sheets. 

You can have your own spreadsheet and modify the code in `App\Http\Controllers\ CertificateGeneratorController` class accordingly.
